version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/svc"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/auth"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/svc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/messaging"
    schedule:
      interval: "weekly"
