// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assign.sql

package sqlc

import (
	"context"
)

const checkEntryPathCollision = `-- name: CheckEntryPathCollision :one
SELECT 1 FROM entries WHERE project_id = ? AND directory_path = ? AND slug = ? AND id != ?
`

type CheckEntryPathCollisionParams struct {
	ProjectID     string `json:"project_id"`
	DirectoryPath string `json:"directory_path"`
	Slug          string `json:"slug"`
	ID            string `json:"id"`
}

func (q *Queries) CheckEntryPathCollision(ctx context.Context, arg CheckEntryPathCollisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEntryPathCollision,
		arg.ProjectID,
		arg.DirectoryPath,
		arg.Slug,
		arg.ID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const rewriteEntryLinkTargets = `-- name: RewriteEntryLinkTargets :exec
UPDATE entry_links SET target_path = ?
WHERE target_path = ? AND entry_id IN (SELECT id FROM entries WHERE project_id = ?)
`

type RewriteEntryLinkTargetsParams struct {
	TargetPath   string `json:"target_path"`
	TargetPath_2 string `json:"target_path_2"`
	ProjectID    string `json:"project_id"`
}

func (q *Queries) RewriteEntryLinkTargets(ctx context.Context, arg RewriteEntryLinkTargetsParams) error {
	_, err := q.db.ExecContext(ctx, rewriteEntryLinkTargets, arg.TargetPath, arg.TargetPath_2, arg.ProjectID)
	return err
}

const updateEntryDirectoryPath = `-- name: UpdateEntryDirectoryPath :exec
UPDATE entries SET directory_path = ?, updated_at = ? WHERE id = ?
`

type UpdateEntryDirectoryPathParams struct {
	DirectoryPath string `json:"directory_path"`
	UpdatedAt     int64  `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateEntryDirectoryPath(ctx context.Context, arg UpdateEntryDirectoryPathParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryDirectoryPath, arg.DirectoryPath, arg.UpdatedAt, arg.ID)
	return err
}
