// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntryMeta = `-- name: GetEntryMeta :one
SELECT id, project_id, slug, directory_path, title, tags, COALESCE(owner_user_id,''), created_at, updated_at, COALESCE(body_hash,''), orphaned_at FROM entries WHERE id = ?
`

type GetEntryMetaRow struct {
	ID            string        `json:"id"`
	ProjectID     string        `json:"project_id"`
	Slug          string        `json:"slug"`
	DirectoryPath string        `json:"directory_path"`
	Title         string        `json:"title"`
	Tags          string        `json:"tags"`
	OwnerUserID   string        `json:"owner_user_id"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	BodyHash      string        `json:"body_hash"`
	OrphanedAt    sql.NullInt64 `json:"orphaned_at"`
}

func (q *Queries) GetEntryMeta(ctx context.Context, id string) (GetEntryMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryMeta, id)
	var i GetEntryMetaRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.DirectoryPath,
		&i.Title,
		&i.Tags,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodyHash,
		&i.OrphanedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO entries (id, project_id, slug, directory_path, title, tags, owner_user_id, created_at, updated_at, body_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEntryParams struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Slug          string         `json:"slug"`
	DirectoryPath string         `json:"directory_path"`
	Title         string         `json:"title"`
	Tags          string         `json:"tags"`
	OwnerUserID   sql.NullString `json:"owner_user_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	BodyHash      sql.NullString `json:"body_hash"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.DirectoryPath,
		arg.Title,
		arg.Tags,
		arg.OwnerUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BodyHash,
	)
	return err
}

const listEntriesForProject = `-- name: ListEntriesForProject :many
SELECT id, project_id, slug, directory_path, title, tags, COALESCE(owner_user_id,''), created_at, updated_at, COALESCE(body_hash,''), orphaned_at FROM entries WHERE project_id = ? ORDER BY directory_path, slug
`

type ListEntriesForProjectRow struct {
	ID            string        `json:"id"`
	ProjectID     string        `json:"project_id"`
	Slug          string        `json:"slug"`
	DirectoryPath string        `json:"directory_path"`
	Title         string        `json:"title"`
	Tags          string        `json:"tags"`
	OwnerUserID   string        `json:"owner_user_id"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	BodyHash      string        `json:"body_hash"`
	OrphanedAt    sql.NullInt64 `json:"orphaned_at"`
}

func (q *Queries) ListEntriesForProject(ctx context.Context, projectID string) ([]ListEntriesForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesForProjectRow
	for rows.Next() {
		var i ListEntriesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.DirectoryPath,
			&i.Title,
			&i.Tags,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyHash,
			&i.OrphanedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries SET slug = ?, directory_path = ?, title = ?, tags = ?, updated_at = ?, body_hash = ? WHERE id = ?
`

type UpdateEntryParams struct {
	Slug          string         `json:"slug"`
	DirectoryPath string         `json:"directory_path"`
	Title         string         `json:"title"`
	Tags          string         `json:"tags"`
	UpdatedAt     int64          `json:"updated_at"`
	BodyHash      sql.NullString `json:"body_hash"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Slug,
		arg.DirectoryPath,
		arg.Title,
		arg.Tags,
		arg.UpdatedAt,
		arg.BodyHash,
		arg.ID,
	)
	return err
}
