// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facets.sql

package sqlc

import (
	"context"
)

const deleteGlobalFacet = `-- name: DeleteGlobalFacet :exec
DELETE FROM facets WHERE name = ?
`

func (q *Queries) DeleteGlobalFacet(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteGlobalFacet, name)
	return err
}

const deleteProjectFacet = `-- name: DeleteProjectFacet :exec
DELETE FROM project_facets WHERE project_id = ? AND name = ?
`

type DeleteProjectFacetParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) DeleteProjectFacet(ctx context.Context, arg DeleteProjectFacetParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectFacet, arg.ProjectID, arg.Name)
	return err
}

const effectiveFacetVocabulary = `-- name: EffectiveFacetVocabulary :many
SELECT name FROM facets
UNION
SELECT name FROM project_facets WHERE project_id = ?
ORDER BY name
`

func (q *Queries) EffectiveFacetVocabulary(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, effectiveFacetVocabulary, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGlobalFacet = `-- name: InsertGlobalFacet :execrows
INSERT OR IGNORE INTO facets (name) VALUES (?)
`

func (q *Queries) InsertGlobalFacet(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertGlobalFacet, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertProjectFacet = `-- name: InsertProjectFacet :exec
INSERT OR IGNORE INTO project_facets (project_id, name) VALUES (?, ?)
`

type InsertProjectFacetParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) InsertProjectFacet(ctx context.Context, arg InsertProjectFacetParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectFacet, arg.ProjectID, arg.Name)
	return err
}

const listGlobalFacetNames = `-- name: ListGlobalFacetNames :many
SELECT name FROM facets ORDER BY name
`

func (q *Queries) ListGlobalFacetNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalFacetNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
