// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: helpers.sql

package sqlc

import (
	"context"
)

const getProjectIDForEntry = `-- name: GetProjectIDForEntry :one
SELECT project_id FROM entries WHERE id = ?
`

func (q *Queries) GetProjectIDForEntry(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectIDForEntry, id)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}
