// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const checkEntrySlugAtPath = `-- name: CheckEntrySlugAtPath :one
SELECT 1 FROM entries WHERE project_id = ? AND directory_path = ? AND slug = ?
`

type CheckEntrySlugAtPathParams struct {
	ProjectID     string `json:"project_id"`
	DirectoryPath string `json:"directory_path"`
	Slug          string `json:"slug"`
}

func (q *Queries) CheckEntrySlugAtPath(ctx context.Context, arg CheckEntrySlugAtPathParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEntrySlugAtPath, arg.ProjectID, arg.DirectoryPath, arg.Slug)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findEntryAtPathForImport = `-- name: FindEntryAtPathForImport :one
SELECT id FROM entries WHERE project_id = ? AND directory_path = ? AND slug = ?
`

type FindEntryAtPathForImportParams struct {
	ProjectID     string `json:"project_id"`
	DirectoryPath string `json:"directory_path"`
	Slug          string `json:"slug"`
}

func (q *Queries) FindEntryAtPathForImport(ctx context.Context, arg FindEntryAtPathForImportParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findEntryAtPathForImport, arg.ProjectID, arg.DirectoryPath, arg.Slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertImportedEntry = `-- name: InsertImportedEntry :exec
INSERT INTO entries (id, project_id, slug, directory_path, title, tags, owner_user_id, created_at, updated_at, body_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertImportedEntryParams struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Slug          string         `json:"slug"`
	DirectoryPath string         `json:"directory_path"`
	Title         string         `json:"title"`
	Tags          string         `json:"tags"`
	OwnerUserID   sql.NullString `json:"owner_user_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	BodyHash      sql.NullString `json:"body_hash"`
}

func (q *Queries) InsertImportedEntry(ctx context.Context, arg InsertImportedEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertImportedEntry,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.DirectoryPath,
		arg.Title,
		arg.Tags,
		arg.OwnerUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BodyHash,
	)
	return err
}

const insertProjectFacetNew = `-- name: InsertProjectFacetNew :exec
INSERT INTO project_facets (project_id, name) VALUES (?, ?)
`

type InsertProjectFacetNewParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) InsertProjectFacetNew(ctx context.Context, arg InsertProjectFacetNewParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectFacetNew, arg.ProjectID, arg.Name)
	return err
}

const updateEntryOverwrite = `-- name: UpdateEntryOverwrite :exec
UPDATE entries SET title = ?, tags = ?, updated_at = ?, body_hash = ? WHERE id = ?
`

type UpdateEntryOverwriteParams struct {
	Title     string         `json:"title"`
	Tags      string         `json:"tags"`
	UpdatedAt int64          `json:"updated_at"`
	BodyHash  sql.NullString `json:"body_hash"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateEntryOverwrite(ctx context.Context, arg UpdateEntryOverwriteParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryOverwrite,
		arg.Title,
		arg.Tags,
		arg.UpdatedAt,
		arg.BodyHash,
		arg.ID,
	)
	return err
}
