// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: internal.sql

package sqlc

import (
	"context"
	"database/sql"
)

const orphanProjectEntries = `-- name: OrphanProjectEntries :execrows
UPDATE entries SET orphaned_at = ? WHERE project_id = ? AND orphaned_at IS NULL
`

type OrphanProjectEntriesParams struct {
	OrphanedAt sql.NullInt64 `json:"orphaned_at"`
	ProjectID  string        `json:"project_id"`
}

func (q *Queries) OrphanProjectEntries(ctx context.Context, arg OrphanProjectEntriesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, orphanProjectEntries, arg.OrphanedAt, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
