// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteEntryLinks = `-- name: DeleteEntryLinks :exec
DELETE FROM entry_links WHERE entry_id = ?
`

func (q *Queries) DeleteEntryLinks(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteEntryLinks, entryID)
	return err
}

const findEntryIDAtPath = `-- name: FindEntryIDAtPath :one
SELECT id FROM entries WHERE project_id = ? AND directory_path = ? AND slug = ?
`

type FindEntryIDAtPathParams struct {
	ProjectID     string `json:"project_id"`
	DirectoryPath string `json:"directory_path"`
	Slug          string `json:"slug"`
}

func (q *Queries) FindEntryIDAtPath(ctx context.Context, arg FindEntryIDAtPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findEntryIDAtPath, arg.ProjectID, arg.DirectoryPath, arg.Slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertEntryLink = `-- name: InsertEntryLink :exec
INSERT INTO entry_links (entry_id, target_path, target_entry_id, label, card_facet, resolved)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEntryLinkParams struct {
	EntryID       string         `json:"entry_id"`
	TargetPath    string         `json:"target_path"`
	TargetEntryID sql.NullString `json:"target_entry_id"`
	Label         string         `json:"label"`
	CardFacet     sql.NullString `json:"card_facet"`
	Resolved      int64          `json:"resolved"`
}

func (q *Queries) InsertEntryLink(ctx context.Context, arg InsertEntryLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertEntryLink,
		arg.EntryID,
		arg.TargetPath,
		arg.TargetEntryID,
		arg.Label,
		arg.CardFacet,
		arg.Resolved,
	)
	return err
}
