// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_handler.sql

package sqlc

import (
	"context"
)

const listDanglingLinksForProject = `-- name: ListDanglingLinksForProject :many
SELECT el.entry_id, el.target_path, el.label
FROM entry_links el
JOIN entries e ON e.id = el.entry_id
WHERE e.project_id = ? AND el.resolved = 0
ORDER BY el.entry_id, el.target_path
`

type ListDanglingLinksForProjectRow struct {
	EntryID    string `json:"entry_id"`
	TargetPath string `json:"target_path"`
	Label      string `json:"label"`
}

func (q *Queries) ListDanglingLinksForProject(ctx context.Context, projectID string) ([]ListDanglingLinksForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listDanglingLinksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDanglingLinksForProjectRow
	for rows.Next() {
		var i ListDanglingLinksForProjectRow
		if err := rows.Scan(&i.EntryID, &i.TargetPath, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryIDsForProject = `-- name: ListEntryIDsForProject :many
SELECT id FROM entries WHERE project_id = ?
`

func (q *Queries) ListEntryIDsForProject(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEntryIDsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLinksForEntry = `-- name: ListEntryLinksForEntry :many
SELECT target_path, COALESCE(target_entry_id, ''), label, COALESCE(card_facet, ''), resolved
FROM entry_links
WHERE entry_id = ?
ORDER BY rowid
`

type ListEntryLinksForEntryRow struct {
	TargetPath    string `json:"target_path"`
	TargetEntryID string `json:"target_entry_id"`
	Label         string `json:"label"`
	CardFacet     string `json:"card_facet"`
	Resolved      int64  `json:"resolved"`
}

func (q *Queries) ListEntryLinksForEntry(ctx context.Context, entryID string) ([]ListEntryLinksForEntryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntryLinksForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntryLinksForEntryRow
	for rows.Next() {
		var i ListEntryLinksForEntryRow
		if err := rows.Scan(
			&i.TargetPath,
			&i.TargetEntryID,
			&i.Label,
			&i.CardFacet,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
