// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type EntriesFt struct {
	EntryID string `json:"entry_id"`
	Title   string `json:"title"`
	Tags    string `json:"tags"`
	Body    string `json:"body"`
}

type Entry struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Slug          string         `json:"slug"`
	DirectoryPath string         `json:"directory_path"`
	Title         string         `json:"title"`
	Tags          string         `json:"tags"`
	OwnerUserID   sql.NullString `json:"owner_user_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	OrphanedAt    sql.NullInt64  `json:"orphaned_at"`
	BodyHash      sql.NullString `json:"body_hash"`
}

type EntryLink struct {
	EntryID       string         `json:"entry_id"`
	TargetPath    string         `json:"target_path"`
	TargetEntryID sql.NullString `json:"target_entry_id"`
	Label         string         `json:"label"`
	CardFacet     sql.NullString `json:"card_facet"`
	Resolved      int64          `json:"resolved"`
}

type Facet struct {
	Name string `json:"name"`
}

type ProjectFacet struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

type SchemaMetum struct {
	ID        int64 `json:"id"`
	CreatedAt int64 `json:"created_at"`
}
