// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"
)

const deleteSearchIndexEntry = `-- name: DeleteSearchIndexEntry :exec
DELETE FROM entries_fts WHERE entry_id = ?
`

func (q *Queries) DeleteSearchIndexEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteSearchIndexEntry, entryID)
	return err
}

const insertSearchIndexEntry = `-- name: InsertSearchIndexEntry :exec
INSERT INTO entries_fts (entry_id, title, tags, body)
VALUES (?, ?, ?, ?)
`

type InsertSearchIndexEntryParams struct {
	EntryID string `json:"entry_id"`
	Title   string `json:"title"`
	Tags    string `json:"tags"`
	Body    string `json:"body"`
}

func (q *Queries) InsertSearchIndexEntry(ctx context.Context, arg InsertSearchIndexEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertSearchIndexEntry,
		arg.EntryID,
		arg.Title,
		arg.Tags,
		arg.Body,
	)
	return err
}
