basePath: /
host: localhost:3003
info:
  contact: {}
  description: Sends transactional email via SMTP.
  title: Quillit Messaging Service API
  version: "1.0"
paths:
  /healthz:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
