// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
)

const adminListProjectMembers = `-- name: AdminListProjectMembers :many
SELECT id, project_id, user_id, role, joined_at, username FROM project_members WHERE project_id = ? ORDER BY joined_at ASC
`

func (q *Queries) AdminListProjectMembers(ctx context.Context, projectID string) ([]ProjectMember, error) {
	rows, err := q.db.QueryContext(ctx, adminListProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProjects = `-- name: AdminListProjects :many

SELECT p.id, p.name, p.type, p.created_by, p.created_at,
       COUNT(pm.id) AS member_count
FROM projects p
LEFT JOIN project_members pm ON pm.project_id = p.id
WHERE p.name LIKE ?
GROUP BY p.id
ORDER BY p.created_at DESC
`

type AdminListProjectsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   int64  `json:"created_at"`
	MemberCount int64  `json:"member_count"`
}

// Queries backing app/svc/internal/handler/admin.go.
func (q *Queries) AdminListProjects(ctx context.Context, name string) ([]AdminListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListProjects, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListProjectsRow
	for rows.Next() {
		var i AdminListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProjectByID = `-- name: CountProjectByID :one
SELECT COUNT(*) FROM projects WHERE id = ?
`

func (q *Queries) CountProjectByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
