// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_ws.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countChatProjectMembership = `-- name: CountChatProjectMembership :one

SELECT COUNT(*) FROM project_members WHERE project_id = ? AND user_id = ?
`

type CountChatProjectMembershipParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

// Queries backing app/svc/internal/handler/chat_ws.go.
func (q *Queries) CountChatProjectMembership(ctx context.Context, arg CountChatProjectMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChatProjectMembership, arg.ProjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRunningGameSessionID = `-- name: GetRunningGameSessionID :one
SELECT id FROM game_sessions WHERE project_id = ? AND status = 'running'
`

func (q *Queries) GetRunningGameSessionID(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRunningGameSessionID, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertChatMessage = `-- name: InsertChatMessage :exec
INSERT INTO chat_messages (id, session_id, project_id, sender_id, type, body, entry_id, card_title, card_body, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChatMessageParams struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	ProjectID string         `json:"project_id"`
	SenderID  string         `json:"sender_id"`
	Type      string         `json:"type"`
	Body      string         `json:"body"`
	EntryID   sql.NullString `json:"entry_id"`
	CardTitle string         `json:"card_title"`
	CardBody  string         `json:"card_body"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertChatMessage,
		arg.ID,
		arg.SessionID,
		arg.ProjectID,
		arg.SenderID,
		arg.Type,
		arg.Body,
		arg.EntryID,
		arg.CardTitle,
		arg.CardBody,
		arg.CreatedAt,
	)
	return err
}
