// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contentproxy.sql

package sqlc

import (
	"context"
)

const checkProjectMembership = `-- name: CheckProjectMembership :one

SELECT 1 FROM project_members WHERE project_id = ? AND user_id = ?
`

type CheckProjectMembershipParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

// Queries backing app/svc/internal/handler/contentproxy.go.
func (q *Queries) CheckProjectMembership(ctx context.Context, arg CheckProjectMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkProjectMembership, arg.ProjectID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
