// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countGameSessionByIDAndProject = `-- name: CountGameSessionByIDAndProject :one
SELECT COUNT(*) FROM game_sessions WHERE id = ? AND project_id = ?
`

type CountGameSessionByIDAndProjectParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CountGameSessionByIDAndProject(ctx context.Context, arg CountGameSessionByIDAndProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGameSessionByIDAndProject, arg.ID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectMembership = `-- name: CountProjectMembership :one

SELECT COUNT(*) FROM project_members WHERE project_id = ? AND user_id = ?
`

type CountProjectMembershipParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

// Queries backing app/svc/internal/handler/game_sessions.go.
func (q *Queries) CountProjectMembership(ctx context.Context, arg CountProjectMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectMembership, arg.ProjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGameSession = `-- name: GetGameSession :one
SELECT id, project_id, status, started_by, started_at, stopped_by, stopped_at FROM game_sessions WHERE id = ?
`

func (q *Queries) GetGameSession(ctx context.Context, id string) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedBy,
		&i.StoppedAt,
	)
	return i, err
}

const getRunningGameSession = `-- name: GetRunningGameSession :one
SELECT id, project_id, status, started_by, started_at, stopped_by, stopped_at FROM game_sessions WHERE project_id = ? AND status = 'running'
`

func (q *Queries) GetRunningGameSession(ctx context.Context, projectID string) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getRunningGameSession, projectID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedBy,
		&i.StoppedAt,
	)
	return i, err
}

const insertGameSession = `-- name: InsertGameSession :exec
INSERT INTO game_sessions (id, project_id, status, started_by, started_at) VALUES (?, ?, 'running', ?, ?)
`

type InsertGameSessionParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	StartedBy string `json:"started_by"`
	StartedAt int64  `json:"started_at"`
}

func (q *Queries) InsertGameSession(ctx context.Context, arg InsertGameSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertGameSession,
		arg.ID,
		arg.ProjectID,
		arg.StartedBy,
		arg.StartedAt,
	)
	return err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, project_id, sender_id, type, body, entry_id, card_title, card_body, created_at
FROM chat_messages WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProjectID,
			&i.SenderID,
			&i.Type,
			&i.Body,
			&i.EntryID,
			&i.CardTitle,
			&i.CardBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameSessionsForProject = `-- name: ListGameSessionsForProject :many
SELECT id, project_id, status, started_by, started_at, stopped_by, stopped_at FROM game_sessions WHERE project_id = ? ORDER BY started_at DESC LIMIT 100
`

func (q *Queries) ListGameSessionsForProject(ctx context.Context, projectID string) ([]GameSession, error) {
	rows, err := q.db.QueryContext(ctx, listGameSessionsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.StartedBy,
			&i.StartedAt,
			&i.StoppedBy,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopGameSession = `-- name: StopGameSession :one
UPDATE game_sessions SET status = 'stopped', stopped_by = ?, stopped_at = ?
WHERE project_id = ? AND status = 'running'
RETURNING id, project_id, status, started_by, started_at, stopped_by, stopped_at
`

type StopGameSessionParams struct {
	StoppedBy sql.NullString `json:"stopped_by"`
	StoppedAt sql.NullInt64  `json:"stopped_at"`
	ProjectID string         `json:"project_id"`
}

func (q *Queries) StopGameSession(ctx context.Context, arg StopGameSessionParams) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, stopGameSession, arg.StoppedBy, arg.StoppedAt, arg.ProjectID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedBy,
		&i.StoppedAt,
	)
	return i, err
}
