// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ChatMessage struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	ProjectID string         `json:"project_id"`
	SenderID  string         `json:"sender_id"`
	Type      string         `json:"type"`
	Body      string         `json:"body"`
	EntryID   sql.NullString `json:"entry_id"`
	CardTitle string         `json:"card_title"`
	CardBody  string         `json:"card_body"`
	CreatedAt int64          `json:"created_at"`
}

type GameSession struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	Status    string         `json:"status"`
	StartedBy string         `json:"started_by"`
	StartedAt int64          `json:"started_at"`
	StoppedBy sql.NullString `json:"stopped_by"`
	StoppedAt sql.NullInt64  `json:"stopped_at"`
}

type Project struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	CreatedBy string `json:"created_by"`
	CreatedAt int64  `json:"created_at"`
}

type ProjectInvite struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	ProjectID string         `json:"project_id"`
	Role      string         `json:"role"`
	CreatedBy string         `json:"created_by"`
	ExpiresAt int64          `json:"expires_at"`
	UsedAt    sql.NullInt64  `json:"used_at"`
	UsedBy    sql.NullString `json:"used_by"`
}

type ProjectMember struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	JoinedAt  int64  `json:"joined_at"`
	Username  string `json:"username"`
}

type Session struct {
	ID        string `json:"id"`
	Jwt       string `json:"jwt"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type UserSetting struct {
	UserID    string `json:"user_id"`
	Settings  string `json:"settings"`
	UpdatedAt int64  `json:"updated_at"`
}
