// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT OR IGNORE INTO project_members (id, project_id, user_id, role, joined_at, username)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddProjectMemberParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	JoinedAt  int64  `json:"joined_at"`
	Username  string `json:"username"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
		arg.Username,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectInvite = `-- name: DeleteProjectInvite :exec
DELETE FROM project_invites WHERE token = ? AND project_id = ?
`

type DeleteProjectInviteParams struct {
	Token     string `json:"token"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteProjectInvite(ctx context.Context, arg DeleteProjectInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectInvite, arg.Token, arg.ProjectID)
	return err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members WHERE project_id = ? AND user_id = ?
`

type DeleteProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT p.type, pm.role
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?
WHERE p.id = ?
`

type GetMemberRoleParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetMemberRoleRow struct {
	Type string `json:"type"`
	Role string `json:"role"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (GetMemberRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.UserID, arg.ID)
	var i GetMemberRoleRow
	err := row.Scan(&i.Type, &i.Role)
	return i, err
}

const getProjectCreatedBy = `-- name: GetProjectCreatedBy :one
SELECT created_by FROM projects WHERE id = ?
`

func (q *Queries) GetProjectCreatedBy(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectCreatedBy, id)
	var created_by string
	err := row.Scan(&created_by)
	return created_by, err
}

const getProjectForMember = `-- name: GetProjectForMember :one
SELECT p.id, p.name, p.type, p.created_by, p.created_at,
       pm.role,
       (SELECT COUNT(*) FROM project_members WHERE project_id = p.id) AS member_count
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?
WHERE p.id = ?
`

type GetProjectForMemberParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetProjectForMemberRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   int64  `json:"created_at"`
	Role        string `json:"role"`
	MemberCount int64  `json:"member_count"`
}

func (q *Queries) GetProjectForMember(ctx context.Context, arg GetProjectForMemberParams) (GetProjectForMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectForMember, arg.UserID, arg.ID)
	var i GetProjectForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Role,
		&i.MemberCount,
	)
	return i, err
}

const getProjectInviteByToken = `-- name: GetProjectInviteByToken :one
SELECT id, project_id, role, expires_at, used_at FROM project_invites WHERE token = ?
`

type GetProjectInviteByTokenRow struct {
	ID        string        `json:"id"`
	ProjectID string        `json:"project_id"`
	Role      string        `json:"role"`
	ExpiresAt int64         `json:"expires_at"`
	UsedAt    sql.NullInt64 `json:"used_at"`
}

func (q *Queries) GetProjectInviteByToken(ctx context.Context, token string) (GetProjectInviteByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectInviteByToken, token)
	var i GetProjectInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Role,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (id, name, type, created_by, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertProjectParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	CreatedBy string `json:"created_by"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertProjectInvite = `-- name: InsertProjectInvite :exec
INSERT INTO project_invites (id, token, project_id, role, created_by, expires_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProjectInviteParams struct {
	ID        string `json:"id"`
	Token     string `json:"token"`
	ProjectID string `json:"project_id"`
	Role      string `json:"role"`
	CreatedBy string `json:"created_by"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) InsertProjectInvite(ctx context.Context, arg InsertProjectInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectInvite,
		arg.ID,
		arg.Token,
		arg.ProjectID,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	return err
}

const insertProjectMember = `-- name: InsertProjectMember :exec
INSERT INTO project_members (id, project_id, user_id, role, joined_at, username)
VALUES (?, ?, ?, ?, ?, '')
`

type InsertProjectMemberParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	JoinedAt  int64  `json:"joined_at"`
}

func (q *Queries) InsertProjectMember(ctx context.Context, arg InsertProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const joinProjectAddMember = `-- name: JoinProjectAddMember :exec
INSERT OR IGNORE INTO project_members (id, project_id, user_id, role, joined_at, username)
VALUES (?, ?, ?, ?, ?, '')
`

type JoinProjectAddMemberParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	JoinedAt  int64  `json:"joined_at"`
}

func (q *Queries) JoinProjectAddMember(ctx context.Context, arg JoinProjectAddMemberParams) error {
	_, err := q.db.ExecContext(ctx, joinProjectAddMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT id, project_id, user_id, username, role, joined_at FROM project_members WHERE project_id = ? ORDER BY joined_at ASC
`

type ListProjectMembersRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	JoinedAt  int64  `json:"joined_at"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many

SELECT p.id, p.name, p.type, p.created_by, p.created_at,
       pm.role,
       (SELECT COUNT(*) FROM project_members WHERE project_id = p.id) AS member_count,
       EXISTS(SELECT 1 FROM game_sessions gs WHERE gs.project_id = p.id AND gs.status = 'running') AS live
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?
WHERE p.type != 'global'
ORDER BY p.created_at DESC
`

type ListProjectsForUserRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   int64  `json:"created_at"`
	Role        string `json:"role"`
	MemberCount int64  `json:"member_count"`
	Live        bool   `json:"live"`
}

// Queries backing app/svc/internal/handler/projects.go.
func (q *Queries) ListProjectsForUser(ctx context.Context, userID string) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForUserRow
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
			&i.MemberCount,
			&i.Live,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectInviteUsed = `-- name: MarkProjectInviteUsed :exec
UPDATE project_invites SET used_at = ?, used_by = ? WHERE id = ?
`

type MarkProjectInviteUsedParams struct {
	UsedAt sql.NullInt64  `json:"used_at"`
	UsedBy sql.NullString `json:"used_by"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkProjectInviteUsed(ctx context.Context, arg MarkProjectInviteUsedParams) error {
	_, err := q.db.ExecContext(ctx, markProjectInviteUsed, arg.UsedAt, arg.UsedBy, arg.ID)
	return err
}

const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects SET name = ? WHERE id = ?
`

type UpdateProjectNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectName, arg.Name, arg.ID)
	return err
}
