// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one

SELECT settings FROM user_settings WHERE user_id = ?
`

// Queries backing app/svc/internal/handler/settings.go.
func (q *Queries) GetUserSettings(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var settings string
	err := row.Scan(&settings)
	return settings, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id, settings, updated_at) VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET settings = excluded.settings, updated_at = excluded.updated_at
`

type UpsertUserSettingsParams struct {
	UserID    string `json:"user_id"`
	Settings  string `json:"settings"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettings, arg.UserID, arg.Settings, arg.UpdatedAt)
	return err
}
