// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*) FROM users WHERE email = ?
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByUsername = `-- name: CountUsersByUsername :one
SELECT COUNT(*) FROM users WHERE username = ?
`

func (q *Queries) CountUsersByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, role, active, created_at FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	Role      string `json:"role"`
	Active    int64  `json:"active"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, password_hash, role, active FROM users WHERE email = ?
`

type GetUserForLoginRow struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Active       int64  `json:"active"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
	)
	return i, err
}

const getUserRoleActive = `-- name: GetUserRoleActive :one
SELECT role, active FROM users WHERE id = ?
`

type GetUserRoleActiveRow struct {
	Role   string `json:"role"`
	Active int64  `json:"active"`
}

func (q *Queries) GetUserRoleActive(ctx context.Context, id string) (GetUserRoleActiveRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleActive, id)
	var i GetUserRoleActiveRow
	err := row.Scan(&i.Role, &i.Active)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :exec
INSERT INTO users (id, email, username, password_hash, role, created_at, updated_at)
VALUES (?, ?, ?, ?, 'admin', ?, ?)
`

type InsertAdminUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, username, password_hash, role, created_at, updated_at)
VALUES (?, ?, ?, ?, 'user', ?, ?)
`

type InsertUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, username FROM users
WHERE email LIKE ? OR username LIKE ?
ORDER BY username
LIMIT 20
`

type SearchUsersParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type SearchUsersRow struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Email, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActive = `-- name: UpdateUserActive :execrows
UPDATE users SET active = ?, updated_at = ? WHERE id = ?
`

type UpdateUserActiveParams struct {
	Active    int64  `json:"active"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserActive, arg.Active, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
