// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlc

import (
	"context"
)

const deleteUnusedResetTokens = `-- name: DeleteUnusedResetTokens :exec
DELETE FROM password_reset_tokens WHERE user_id = ? AND used = 0
`

func (q *Queries) DeleteUnusedResetTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedResetTokens, userID)
	return err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE email = ?
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getValidResetToken = `-- name: GetValidResetToken :one
SELECT id, user_id FROM password_reset_tokens
WHERE token_hash = ? AND used = 0 AND expires_at > ?
`

type GetValidResetTokenParams struct {
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

type GetValidResetTokenRow struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetValidResetToken(ctx context.Context, arg GetValidResetTokenParams) (GetValidResetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getValidResetToken, arg.TokenHash, arg.ExpiresAt)
	var i GetValidResetTokenRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const insertResetToken = `-- name: InsertResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at, used, created_at)
VALUES (?, ?, ?, ?, 0, ?)
`

type InsertResetTokenParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertResetToken(ctx context.Context, arg InsertResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const markResetTokenUsed = `-- name: MarkResetTokenUsed :exec
UPDATE password_reset_tokens SET used = 1 WHERE id = ?
`

func (q *Queries) MarkResetTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markResetTokenUsed, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
